/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica2.frontend;

import java.awt.Color;
//import practica2.backend.jugador.Jugador;
import practica2.backend.piezas.Alfil;
import practica2.backend.piezas.Torre;


/**
 *
 * @author astridmc
 */
public class EscogerPieza extends javax.swing.JDialog {

    /**
     * Creates new form EscogerPieza
     */
    public EscogerPieza() {
        diseño();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiqueta1 = new javax.swing.JLabel();
        btnAlfil = new javax.swing.JButton();
        btnTorre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(253, 222, 190));

        jPanel1.setBackground(new java.awt.Color(251, 224, 178));

        etiqueta1.setFont(new java.awt.Font("Century Schoolbook L", 1, 20)); // NOI18N
        etiqueta1.setText("Que Pieza Desea Colocar en el Tablero?");

        btnAlfil.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        btnAlfil.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btnAlfil.setForeground(new java.awt.Color(230, 92, 7));
        btnAlfil.setText("ALFIL");
        btnAlfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlfilActionPerformed(evt);
            }
        });

        btnTorre.setBackground(new java.awt.Color(248, 194, 67));
        btnTorre.setFont(new java.awt.Font("Century Schoolbook L", 1, 24)); // NOI18N
        btnTorre.setForeground(new java.awt.Color(230, 92, 7));
        btnTorre.setText("TORRE");
        btnTorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTorreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlfil, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(etiqueta1)
                .addGap(18, 18, 18)
                .addComponent(btnAlfil)
                .addGap(18, 18, 18)
                .addComponent(btnTorre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    private void btnAlfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlfilActionPerformed
       // System.out.println( TableroAjedrez.getFila());
        Alfil alfil = new Alfil();
        Juego.nuevo.setNoPiezas(Juego.nuevo.getNoPiezas()+1);
        Juego.piezasEtiqueta.setText(Juego.nuevo.getNoPiezas()+ " piezas");
        System.out.println(Juego.nuevo.getNoPiezas());
        Juego.nuevo.sumarPuntos();
        alfil.movimiento();
        alfil.camino();
        Alfil.agregarImagen();
        
        this.setVisible(false);
    }//GEN-LAST:event_btnAlfilActionPerformed

    private void btnTorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTorreActionPerformed
        Torre torre = new Torre();
        Juego.nuevo.setNoPiezas(Juego.nuevo.getNoPiezas()+1);
        Juego.piezasEtiqueta.setText(Juego.nuevo.getNoPiezas()+ " piezas");
        System.out.println(Juego.nuevo.getNoPiezas());
        Juego.nuevo.sumarPuntos();
        torre.movimiento();
        torre.camino();
        Torre.agregarImagen();
        this.setVisible(false);
    }//GEN-LAST:event_btnTorreActionPerformed

    
    public void diseño(){
        this.setBackground(Color.yellow);
        this.setLocationRelativeTo(null);
    }
    
    @Override
    public void setVisible(boolean visible){
        if (visible){
            diseño();
        }
        super.setVisible(visible);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlfil;
    private javax.swing.JButton btnTorre;
    private javax.swing.JLabel etiqueta1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
